# REMEMBER TO EDIT THIS BEFORE DEPLOYING!!!

# the path to your blog's icon:
favicon: /favicon.png

# the path to manifest.json
manifest: /manifest.json

# show excerpt on post list
show_excerpt: true

# light/dark/auto color scheme
color_scheme: auto

# show floating color theme toggle
show_color_scheme_toggle: true

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: Mrs.W.M.s' Technomancer-Cat Coffee
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    Friends: /friends
    Projects: /projects
    About: /about
    # these will be automatically be an icon
    GitHub: https://github.com/Sup0rsonic
      #CodePen: https://codepen.io/mrwillcom
      #Patreon: https://www.patreon.com/MrWillCom
      #Mastodon: https://noc.social/@MrWillCom

# footer items
footer:
  # the title
  Blog:
    # the items after the title, display as links
    Blog: /
    Archives: /archives
    Friends: /friends
    Projects: /projects
    Resume: /resume
    About: /about
    RSS: /atom.xml
  # also the title
  Projects:
    # the items
    #RSA CLI: https://github.com/MrWillCom/rsa-cli
    Hexo Theme Cupertino: https://github.com/MrWillCom/hexo-theme-cupertino
      #A Calendar: https://github.com/MrWillCom/a-calendar
      #Auto Mirroring Bucket: https://github.com/MrWillCom/auto-mirroring-bucket
  # the title
  Me:
    # items
    GitHub: https://github.com/Sup0rsonic
      #CodePen: https://codepen.io/mrwillcom
      #Patreon: https://www.patreon.com/MrWillCom
      #Mastodon: https://noc.social/@MrWillCom
    Email: mailto:1nt3rcepter@gmail.com

# the license your posts under
license: CC BY-NC-SA 4.0, or modded IDGAF License
# the link of your license
license_link: https://github.com/Sup0rsonic/IDGAFPL-WINTERMUTE-MOD/blob/main/LICENSE_CN 

# REMEMBER TO EDIT THIS BEFORE DEPLOY!!!
